name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    env:
      VERSION_STAMP: ""
    runs-on: windows-latest

    steps:      
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish win64
      run: dotnet publish .\src\RestLittle.UI\RestLittle.UI.csproj --runtime win-x64 -c Release -o releases/win-x64/ --self-contained
      
    - name: Zip win64
      uses: vimtor/action-zip@v1
      with:
        # Files or directories to zip
        files: |
          releases/win-x64/
        # Name of output zip file
        dest: "1.0.0.${{ github.GITHUB_RUN_NUMBER }}-win64.zip"
        recursive: true
        
    - name: Publish win86
      run: dotnet publish .\src\RestLittle.UI\RestLittle.UI.csproj --runtime win-x86 -c Release -o releases/win-x86/ --self-contained
      
    - name: Zip win86
      uses: vimtor/action-zip@v1
      with:
        # Files or directories to zip
        files: |
          releases/win-x86/
        # Name of output zip file
        dest: "1.0.0.${{ github.GITHUB_RUN_NUMBER }}-win86.zip"
    
    - name: Release win64
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "1.0.0.${{ github.GITHUB_RUN_NUMBER }}"
          prerelease: false
          title: "Release 1.0.0.${{ github.GITHUB_RUN_NUMBER }}"
          files: |
            "1.0.0.${{ github.GITHUB_RUN_NUMBER }}-win64.zip"
            "1.0.0.${{ github.GITHUB_RUN_NUMBER }}-win86.zip"
