name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish win64
      run: dotnet publish .\src\RestLittle.UI\RestLittle.UI.csproj --runtime win-x64 -c Release -o release/win-x64/ --self-contained
    - name: Publish win86
      run: dotnet publish .\src\RestLittle.UI\RestLittle.UI.csproj --runtime win-x86 -c Release -o release/win-x86/ --self-contained
    - name: Release win-x64
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_COMPRESS: xz
        GHR_PATH: release/win-x64
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release win-x86
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_COMPRESS: xz
        GHR_PATH: release/win-x86
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
