name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish win64
      run: dotnet publish .\src\RestLittle.UI\TakeABreak.UI.csproj --runtime win-x64 -c Release -o release/win-x64/ --self-contained
    - name: Package win-x64
      run: Compress-Archive -Path release/win-x64/ -DestinationPath Take-A-Break-win-x64.zip
    - name: Publish win-x86
      run: dotnet publish .\src\RestLittle.UI\TakeABreak.UI.csproj --runtime win-x86 -c Release -o release/win-x86/ --self-contained
    - name: Package win-x86
      run: Compress-Archive -Path release/win-x86/ -DestinationPath Take-A-Break-win-x84.zip
    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "1.0.0.${{ vars.GITHUB_RUN_NUMBER }}"
          files: |
            Take-A-Break-win-x84.zip
            Take-A-Break-win-x64.zip
